/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pages';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '@angular/http/src/http';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from 'ionic-angular/platform/platform';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import39 from 'ionic-angular/components/navbar/navbar';
import * as import40 from 'ionic-angular/components/label/label';
import * as import41 from '@angular/forms/src/directives/ng_model';
import * as import42 from '@angular/forms/src/directives/ng_control';
import * as import43 from '@angular/forms/src/directives/ng_control_status';
import * as import44 from 'ionic-angular/components/input/input';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/list/list';
import * as import47 from 'ionic-angular/components/button/button';
import * as import48 from 'ionic-angular/components/content/content';
export class Wrapper_SignUp {
  context:import0.SignUp;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.SignUp(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SignUp_Host:import2.RenderComponentType = (null as any);
class _View_SignUp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SignUp_0_4:Wrapper_SignUp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignUp_Host0,renderType_SignUp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('signup',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignUp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignUp_0_4 = new Wrapper_SignUp(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.Http));
    this._appEl_0.initComponent(this._SignUp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SignUp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SignUp) && (0 === requestNodeIndex))) { return this._SignUp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SignUp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignUp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SignUp_Host === (null as any))) { (renderType_SignUp_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignUp_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignUpNgFactory:import13.ComponentFactory<import0.SignUp> = new import13.ComponentFactory<import0.SignUp>('signup',viewFactory_SignUp_Host0,import0.SignUp);
const styles_SignUp:any[] = ([] as any[]);
var renderType_SignUp:import2.RenderComponentType = (null as any);
class _View_SignUp0 extends import1.AppView<import0.SignUp> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import14.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import15.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import16.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import17.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _List_12_3:import18.Wrapper_List;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Item_14_4:import19.Wrapper_Item;
  _ItemContent_14_5:import19.Wrapper_ItemContent;
  _query_Label_14_0:import20.QueryList<any>;
  _query_Button_14_1:import20.QueryList<any>;
  _query_Icon_14_2:import20.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Label_16_3:import21.Wrapper_Label;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _NgModel_19_4:import22.Wrapper_NgModel;
  _NgControl_19_5:any;
  _NgControlStatus_19_6:import23.Wrapper_NgControlStatus;
  _TextInput_19_7:import24.Wrapper_TextInput;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _Item_22_4:import19.Wrapper_Item;
  _ItemContent_22_5:import19.Wrapper_ItemContent;
  _query_Label_22_0:import20.QueryList<any>;
  _query_Button_22_1:import20.QueryList<any>;
  _query_Icon_22_2:import20.QueryList<any>;
  _text_23:any;
  _el_24:any;
  _Label_24_3:import21.Wrapper_Label;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _NgModel_27_4:import22.Wrapper_NgModel;
  _NgControl_27_5:any;
  _NgControlStatus_27_6:import23.Wrapper_NgControlStatus;
  _TextInput_27_7:import24.Wrapper_TextInput;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Item_30_4:import19.Wrapper_Item;
  _ItemContent_30_5:import19.Wrapper_ItemContent;
  _query_Label_30_0:import20.QueryList<any>;
  _query_Button_30_1:import20.QueryList<any>;
  _query_Icon_30_2:import20.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _Label_32_3:import21.Wrapper_Label;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _NgModel_35_4:import22.Wrapper_NgModel;
  _NgControl_35_5:any;
  _NgControlStatus_35_6:import23.Wrapper_NgControlStatus;
  _TextInput_35_7:import24.Wrapper_TextInput;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Item_38_4:import19.Wrapper_Item;
  _ItemContent_38_5:import19.Wrapper_ItemContent;
  _query_Label_38_0:import20.QueryList<any>;
  _query_Button_38_1:import20.QueryList<any>;
  _query_Icon_38_2:import20.QueryList<any>;
  _text_39:any;
  _el_40:any;
  _Label_40_3:import21.Wrapper_Label;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _NgModel_43_4:import22.Wrapper_NgModel;
  _NgControl_43_5:any;
  _NgControlStatus_43_6:import23.Wrapper_NgControlStatus;
  _TextInput_43_7:import24.Wrapper_TextInput;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Item_46_4:import19.Wrapper_Item;
  _ItemContent_46_5:import19.Wrapper_ItemContent;
  _query_Label_46_0:import20.QueryList<any>;
  _query_Button_46_1:import20.QueryList<any>;
  _query_Icon_46_2:import20.QueryList<any>;
  _text_47:any;
  _el_48:any;
  _Label_48_3:import21.Wrapper_Label;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import3.AppElement;
  _NgModel_51_4:import22.Wrapper_NgModel;
  _NgControl_51_5:any;
  _NgControlStatus_51_6:import23.Wrapper_NgControlStatus;
  _TextInput_51_7:import24.Wrapper_TextInput;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import3.AppElement;
  _Item_54_4:import19.Wrapper_Item;
  _ItemContent_54_5:import19.Wrapper_ItemContent;
  _query_Label_54_0:import20.QueryList<any>;
  _query_Button_54_1:import20.QueryList<any>;
  _query_Icon_54_2:import20.QueryList<any>;
  _text_55:any;
  _el_56:any;
  _Label_56_3:import21.Wrapper_Label;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import3.AppElement;
  _NgModel_59_4:import22.Wrapper_NgModel;
  _NgControl_59_5:any;
  _NgControlStatus_59_6:import23.Wrapper_NgControlStatus;
  _TextInput_59_7:import24.Wrapper_TextInput;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import3.AppElement;
  _Button_65_4:import25.Wrapper_Button;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  /*private*/ _appEl_68:import3.AppElement;
  _Button_68_4:import25.Wrapper_Button;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignUp0,renderType_SignUp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import14.Wrapper_Header(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import28.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import15.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import15.Wrapper_Navbar(this.parentInjector.get(import29.App),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import16.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import16.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Create a Account into PhoneChat',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import17.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import17.Wrapper_Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_12_3 = new import18.Wrapper_List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import34.GestureController));
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this._appEl_14 = new import3.AppElement(14,12,this,this._el_14);
    var compView_14:any = import19.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import19.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_14_5 = new import19.Wrapper_ItemContent();
    this._query_Label_14_0 = new import20.QueryList<any>();
    this._query_Button_14_1 = new import20.QueryList<any>();
    this._query_Icon_14_2 = new import20.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_16,'color','primary');
    this.renderer.setElementAttribute(this._el_16,'stacked','');
    this._Label_16_3 = new import21.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_16),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'User name',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_19,'placeholder','User Name (Used to login)');
    this.renderer.setElementAttribute(this._el_19,'type','text');
    this._appEl_19 = new import3.AppElement(19,14,this,this._el_19);
    var compView_19:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(19),this._appEl_19);
    this._NgModel_19_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_19_5 = this._NgModel_19_4.context;
    this._NgControlStatus_19_6 = new import23.Wrapper_NgControlStatus(this._NgControl_19_5);
    this._TextInput_19_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_14_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import37.Platform),new import27.ElementRef(this._el_19),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_19_5);
    this._appEl_19.initComponent(this._TextInput_19_7.context,([] as any[]),compView_19);
    compView_19.create(this._TextInput_19_7.context,([] as any[]),(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_14_0.reset([this._Label_16_3.context]);
    this._Item_14_4.context.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_16]),
      ([] as any[]).concat([
        this._text_15,
        this._text_18,
        this._text_20
      ]
      ),
      ([] as any[]).concat([this._el_19]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item item-block');
    this._appEl_22 = new import3.AppElement(22,12,this,this._el_22);
    var compView_22:any = import19.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import19.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_22_5 = new import19.Wrapper_ItemContent();
    this._query_Label_22_0 = new import20.QueryList<any>();
    this._query_Button_22_1 = new import20.QueryList<any>();
    this._query_Icon_22_2 = new import20.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4.context,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_24,'color','primary');
    this.renderer.setElementAttribute(this._el_24,'stacked','');
    this._Label_24_3 = new import21.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_24),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Name',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_27,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_27,'type','text');
    this._appEl_27 = new import3.AppElement(27,22,this,this._el_27);
    var compView_27:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(27),this._appEl_27);
    this._NgModel_27_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_27_5 = this._NgModel_27_4.context;
    this._NgControlStatus_27_6 = new import23.Wrapper_NgControlStatus(this._NgControl_27_5);
    this._TextInput_27_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_22_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import37.Platform),new import27.ElementRef(this._el_27),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_27_5);
    this._appEl_27.initComponent(this._TextInput_27_7.context,([] as any[]),compView_27);
    compView_27.create(this._TextInput_27_7.context,([] as any[]),(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_22_0.reset([this._Label_24_3.context]);
    this._Item_22_4.context.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_24]),
      ([] as any[]).concat([
        this._text_23,
        this._text_26,
        this._text_28
      ]
      ),
      ([] as any[]).concat([this._el_27]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','item item-block');
    this._appEl_30 = new import3.AppElement(30,12,this,this._el_30);
    var compView_30:any = import19.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Item_30_4 = new import19.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_30),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_30_5 = new import19.Wrapper_ItemContent();
    this._query_Label_30_0 = new import20.QueryList<any>();
    this._query_Button_30_1 = new import20.QueryList<any>();
    this._query_Icon_30_2 = new import20.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_32,'color','primary');
    this.renderer.setElementAttribute(this._el_32,'stacked','');
    this._Label_32_3 = new import21.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_32),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Last Name',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_35,'placeholder','Last Name');
    this.renderer.setElementAttribute(this._el_35,'type','text');
    this._appEl_35 = new import3.AppElement(35,30,this,this._el_35);
    var compView_35:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(35),this._appEl_35);
    this._NgModel_35_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_35_5 = this._NgModel_35_4.context;
    this._NgControlStatus_35_6 = new import23.Wrapper_NgControlStatus(this._NgControl_35_5);
    this._TextInput_35_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_30_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import37.Platform),new import27.ElementRef(this._el_35),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_35_5);
    this._appEl_35.initComponent(this._TextInput_35_7.context,([] as any[]),compView_35);
    compView_35.create(this._TextInput_35_7.context,([] as any[]),(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_30_0.reset([this._Label_32_3.context]);
    this._Item_30_4.context.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_32]),
      ([] as any[]).concat([
        this._text_31,
        this._text_34,
        this._text_36
      ]
      ),
      ([] as any[]).concat([this._el_35]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_37 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','item item-block');
    this._appEl_38 = new import3.AppElement(38,12,this,this._el_38);
    var compView_38:any = import19.viewFactory_Item0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Item_38_4 = new import19.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_38),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_38_5 = new import19.Wrapper_ItemContent();
    this._query_Label_38_0 = new import20.QueryList<any>();
    this._query_Button_38_1 = new import20.QueryList<any>();
    this._query_Icon_38_2 = new import20.QueryList<any>();
    this._appEl_38.initComponent(this._Item_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_40,'color','primary');
    this.renderer.setElementAttribute(this._el_40,'stacked','');
    this._Label_40_3 = new import21.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_40),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Email',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_43,'placeholder','Your Email');
    this.renderer.setElementAttribute(this._el_43,'type','email');
    this._appEl_43 = new import3.AppElement(43,38,this,this._el_43);
    var compView_43:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(43),this._appEl_43);
    this._NgModel_43_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_43_5 = this._NgModel_43_4.context;
    this._NgControlStatus_43_6 = new import23.Wrapper_NgControlStatus(this._NgControl_43_5);
    this._TextInput_43_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_38_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import37.Platform),new import27.ElementRef(this._el_43),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_43_5);
    this._appEl_43.initComponent(this._TextInput_43_7.context,([] as any[]),compView_43);
    compView_43.create(this._TextInput_43_7.context,([] as any[]),(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_38_0.reset([this._Label_40_3.context]);
    this._Item_38_4.context.contentLabel = this._query_Label_38_0.first;
    compView_38.create(this._Item_38_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_40]),
      ([] as any[]).concat([
        this._text_39,
        this._text_42,
        this._text_44
      ]
      ),
      ([] as any[]).concat([this._el_43]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','item item-block');
    this._appEl_46 = new import3.AppElement(46,12,this,this._el_46);
    var compView_46:any = import19.viewFactory_Item0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Item_46_4 = new import19.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_46),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_46_5 = new import19.Wrapper_ItemContent();
    this._query_Label_46_0 = new import20.QueryList<any>();
    this._query_Button_46_1 = new import20.QueryList<any>();
    this._query_Icon_46_2 = new import20.QueryList<any>();
    this._appEl_46.initComponent(this._Item_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_48,'color','primary');
    this.renderer.setElementAttribute(this._el_48,'stacked','');
    this._Label_48_3 = new import21.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_48),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Password',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_51 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_51,'placeholder','Your Password');
    this.renderer.setElementAttribute(this._el_51,'type','password');
    this._appEl_51 = new import3.AppElement(51,46,this,this._el_51);
    var compView_51:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(51),this._appEl_51);
    this._NgModel_51_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_51_5 = this._NgModel_51_4.context;
    this._NgControlStatus_51_6 = new import23.Wrapper_NgControlStatus(this._NgControl_51_5);
    this._TextInput_51_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_46_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import37.Platform),new import27.ElementRef(this._el_51),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_51_5);
    this._appEl_51.initComponent(this._TextInput_51_7.context,([] as any[]),compView_51);
    compView_51.create(this._TextInput_51_7.context,([] as any[]),(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_46_0.reset([this._Label_48_3.context]);
    this._Item_46_4.context.contentLabel = this._query_Label_46_0.first;
    compView_46.create(this._Item_46_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_48]),
      ([] as any[]).concat([
        this._text_47,
        this._text_50,
        this._text_52
      ]
      ),
      ([] as any[]).concat([this._el_51]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_53 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','item item-block');
    this._appEl_54 = new import3.AppElement(54,12,this,this._el_54);
    var compView_54:any = import19.viewFactory_Item0(this.viewUtils,this.injector(54),this._appEl_54);
    this._Item_54_4 = new import19.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_54),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_54_5 = new import19.Wrapper_ItemContent();
    this._query_Label_54_0 = new import20.QueryList<any>();
    this._query_Button_54_1 = new import20.QueryList<any>();
    this._query_Icon_54_2 = new import20.QueryList<any>();
    this._appEl_54.initComponent(this._Item_54_4.context,([] as any[]),compView_54);
    this._text_55 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_56,'color','primary');
    this.renderer.setElementAttribute(this._el_56,'stacked','');
    this._Label_56_3 = new import21.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_56),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Check password',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_59 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_59,'placeholder','Retype Password');
    this.renderer.setElementAttribute(this._el_59,'type','password');
    this._appEl_59 = new import3.AppElement(59,54,this,this._el_59);
    var compView_59:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(59),this._appEl_59);
    this._NgModel_59_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_59_5 = this._NgModel_59_4.context;
    this._NgControlStatus_59_6 = new import23.Wrapper_NgControlStatus(this._NgControl_59_5);
    this._TextInput_59_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_54_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import37.Platform),new import27.ElementRef(this._el_59),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_59_5);
    this._appEl_59.initComponent(this._TextInput_59_7.context,([] as any[]),compView_59);
    compView_59.create(this._TextInput_59_7.context,([] as any[]),(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_54_0.reset([this._Label_56_3.context]);
    this._Item_54_4.context.contentLabel = this._query_Label_54_0.first;
    compView_54.create(this._Item_54_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_56]),
      ([] as any[]).concat([
        this._text_55,
        this._text_58,
        this._text_60
      ]
      ),
      ([] as any[]).concat([this._el_59]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_61 = this.renderer.createText(this._el_12,'\n\n  ',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_63,'padding','');
    this._text_64 = this.renderer.createText(this._el_63,'\n    ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_63,'button',(null as any));
    this.renderer.setElementAttribute(this._el_65,'block','');
    this.renderer.setElementAttribute(this._el_65,'ion-button','');
    this.renderer.setElementAttribute(this._el_65,'type','button');
    this._appEl_65 = new import3.AppElement(65,63,this,this._el_65);
    var compView_65:any = import25.viewFactory_Button0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Button_65_4 = new import25.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_65),this.renderer);
    this._appEl_65.initComponent(this._Button_65_4.context,([] as any[]),compView_65);
    this._text_66 = this.renderer.createText((null as any),'Create Account',(null as any));
    compView_65.create(this._Button_65_4.context,[([] as any[]).concat([this._text_66])],(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n    ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_63,'button',(null as any));
    this.renderer.setElementAttribute(this._el_68,'block','');
    this.renderer.setElementAttribute(this._el_68,'ion-button','');
    this.renderer.setElementAttribute(this._el_68,'type','button');
    this._appEl_68 = new import3.AppElement(68,63,this,this._el_68);
    var compView_68:any = import25.viewFactory_Button0(this.viewUtils,this.injector(68),this._appEl_68);
    this._Button_68_4 = new import25.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_68),this.renderer);
    this._appEl_68.initComponent(this._Button_68_4.context,([] as any[]),compView_68);
    this._text_69 = this.renderer.createText((null as any),'Have an account?',(null as any));
    compView_68.create(this._Button_68_4.context,[([] as any[]).concat([this._text_69])],(null as any));
    this._text_70 = this.renderer.createText(this._el_63,'\n  ',(null as any));
    this._text_71 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_62,
        this._el_63,
        this._text_71
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_72 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'ngModelChange',this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    const subscription_0:any = this._NgModel_19_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_27,'ngModelChange',this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    const subscription_1:any = this._NgModel_27_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_35,'ngModelChange',this.eventHandler(this._handle_ngModelChange_35_0.bind(this)));
    const subscription_2:any = this._NgModel_35_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_35_0.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_43,'ngModelChange',this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    const subscription_3:any = this._NgModel_43_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_51,'ngModelChange',this.eventHandler(this._handle_ngModelChange_51_0.bind(this)));
    const subscription_4:any = this._NgModel_51_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_51_0.bind(this)));
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_59,'ngModelChange',this.eventHandler(this._handle_ngModelChange_59_0.bind(this)));
    const subscription_5:any = this._NgModel_59_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_59_0.bind(this)));
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_65,'click',this.eventHandler(this._handle_click_65_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_68,'click',this.eventHandler(this._handle_click_68_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4,
      subscription_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import39.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import30.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import40.Label) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Label_16_3.context; }
    if (((token === import41.NgModel) && (19 === requestNodeIndex))) { return this._NgModel_19_4.context; }
    if (((token === import42.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_5; }
    if (((token === import43.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_6.context; }
    if (((token === import44.TextInput) && (19 === requestNodeIndex))) { return this._TextInput_19_7.context; }
    if (((token === import45.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_14_4.context; }
    if (((token === import45.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemContent_14_5.context; }
    if (((token === import40.Label) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Label_24_3.context; }
    if (((token === import41.NgModel) && (27 === requestNodeIndex))) { return this._NgModel_27_4.context; }
    if (((token === import42.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_5; }
    if (((token === import43.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_6.context; }
    if (((token === import44.TextInput) && (27 === requestNodeIndex))) { return this._TextInput_27_7.context; }
    if (((token === import45.Item) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_22_4.context; }
    if (((token === import45.ItemContent) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_22_5.context; }
    if (((token === import40.Label) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Label_32_3.context; }
    if (((token === import41.NgModel) && (35 === requestNodeIndex))) { return this._NgModel_35_4.context; }
    if (((token === import42.NgControl) && (35 === requestNodeIndex))) { return this._NgControl_35_5; }
    if (((token === import43.NgControlStatus) && (35 === requestNodeIndex))) { return this._NgControlStatus_35_6.context; }
    if (((token === import44.TextInput) && (35 === requestNodeIndex))) { return this._TextInput_35_7.context; }
    if (((token === import45.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Item_30_4.context; }
    if (((token === import45.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ItemContent_30_5.context; }
    if (((token === import40.Label) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Label_40_3.context; }
    if (((token === import41.NgModel) && (43 === requestNodeIndex))) { return this._NgModel_43_4.context; }
    if (((token === import42.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_5; }
    if (((token === import43.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_6.context; }
    if (((token === import44.TextInput) && (43 === requestNodeIndex))) { return this._TextInput_43_7.context; }
    if (((token === import45.Item) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_38_4.context; }
    if (((token === import45.ItemContent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_38_5.context; }
    if (((token === import40.Label) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Label_48_3.context; }
    if (((token === import41.NgModel) && (51 === requestNodeIndex))) { return this._NgModel_51_4.context; }
    if (((token === import42.NgControl) && (51 === requestNodeIndex))) { return this._NgControl_51_5; }
    if (((token === import43.NgControlStatus) && (51 === requestNodeIndex))) { return this._NgControlStatus_51_6.context; }
    if (((token === import44.TextInput) && (51 === requestNodeIndex))) { return this._TextInput_51_7.context; }
    if (((token === import45.Item) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Item_46_4.context; }
    if (((token === import45.ItemContent) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ItemContent_46_5.context; }
    if (((token === import40.Label) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Label_56_3.context; }
    if (((token === import41.NgModel) && (59 === requestNodeIndex))) { return this._NgModel_59_4.context; }
    if (((token === import42.NgControl) && (59 === requestNodeIndex))) { return this._NgControl_59_5; }
    if (((token === import43.NgControlStatus) && (59 === requestNodeIndex))) { return this._NgControlStatus_59_6.context; }
    if (((token === import44.TextInput) && (59 === requestNodeIndex))) { return this._TextInput_59_7.context; }
    if (((token === import45.Item) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Item_54_4.context; }
    if (((token === import45.ItemContent) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ItemContent_54_5.context; }
    if (((token === import46.List) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._List_12_3.context; }
    if (((token === import47.Button) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Button_65_4.context; }
    if (((token === import47.Button) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Button_68_4.context; }
    if (((token === import48.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._List_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Item_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._ItemContent_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    const currVal_3:any = 'primary';
    this._Label_16_3.check_color(currVal_3,throwOnChange,false);
    this._Label_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_5:any = this.context.userName;
    this._NgModel_19_4.check_model(currVal_5,throwOnChange,false);
    this._NgModel_19_4.detectChangesInternal(this,this._el_19,throwOnChange);
    this._NgControlStatus_19_6.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_12:any = 'User Name (Used to login)';
    this._TextInput_19_7.check_placeholder(currVal_12,throwOnChange,false);
    const currVal_13:any = 'text';
    this._TextInput_19_7.check_type(currVal_13,throwOnChange,false);
    this._TextInput_19_7.detectChangesInternal(this,this._el_19,throwOnChange);
    if (this._Item_22_4.detectChangesInternal(this,this._el_22,throwOnChange)) { this._appEl_22.componentView.markAsCheckOnce(); }
    this._ItemContent_22_5.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_14:any = 'primary';
    this._Label_24_3.check_color(currVal_14,throwOnChange,false);
    this._Label_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_16:any = this.context.name;
    this._NgModel_27_4.check_model(currVal_16,throwOnChange,false);
    this._NgModel_27_4.detectChangesInternal(this,this._el_27,throwOnChange);
    this._NgControlStatus_27_6.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_23:any = 'Name';
    this._TextInput_27_7.check_placeholder(currVal_23,throwOnChange,false);
    const currVal_24:any = 'text';
    this._TextInput_27_7.check_type(currVal_24,throwOnChange,false);
    this._TextInput_27_7.detectChangesInternal(this,this._el_27,throwOnChange);
    if (this._Item_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    this._ItemContent_30_5.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_25:any = 'primary';
    this._Label_32_3.check_color(currVal_25,throwOnChange,false);
    this._Label_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_27:any = this.context.lastName;
    this._NgModel_35_4.check_model(currVal_27,throwOnChange,false);
    this._NgModel_35_4.detectChangesInternal(this,this._el_35,throwOnChange);
    this._NgControlStatus_35_6.detectChangesInternal(this,this._el_35,throwOnChange);
    const currVal_34:any = 'Last Name';
    this._TextInput_35_7.check_placeholder(currVal_34,throwOnChange,false);
    const currVal_35:any = 'text';
    this._TextInput_35_7.check_type(currVal_35,throwOnChange,false);
    this._TextInput_35_7.detectChangesInternal(this,this._el_35,throwOnChange);
    if (this._Item_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    this._ItemContent_38_5.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_36:any = 'primary';
    this._Label_40_3.check_color(currVal_36,throwOnChange,false);
    this._Label_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_38:any = this.context.email;
    this._NgModel_43_4.check_model(currVal_38,throwOnChange,false);
    this._NgModel_43_4.detectChangesInternal(this,this._el_43,throwOnChange);
    this._NgControlStatus_43_6.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_45:any = 'Your Email';
    this._TextInput_43_7.check_placeholder(currVal_45,throwOnChange,false);
    const currVal_46:any = 'email';
    this._TextInput_43_7.check_type(currVal_46,throwOnChange,false);
    this._TextInput_43_7.detectChangesInternal(this,this._el_43,throwOnChange);
    if (this._Item_46_4.detectChangesInternal(this,this._el_46,throwOnChange)) { this._appEl_46.componentView.markAsCheckOnce(); }
    this._ItemContent_46_5.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_47:any = 'primary';
    this._Label_48_3.check_color(currVal_47,throwOnChange,false);
    this._Label_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_49:any = this.context.password;
    this._NgModel_51_4.check_model(currVal_49,throwOnChange,false);
    this._NgModel_51_4.detectChangesInternal(this,this._el_51,throwOnChange);
    this._NgControlStatus_51_6.detectChangesInternal(this,this._el_51,throwOnChange);
    const currVal_56:any = 'Your Password';
    this._TextInput_51_7.check_placeholder(currVal_56,throwOnChange,false);
    const currVal_57:any = 'password';
    this._TextInput_51_7.check_type(currVal_57,throwOnChange,false);
    this._TextInput_51_7.detectChangesInternal(this,this._el_51,throwOnChange);
    if (this._Item_54_4.detectChangesInternal(this,this._el_54,throwOnChange)) { this._appEl_54.componentView.markAsCheckOnce(); }
    this._ItemContent_54_5.detectChangesInternal(this,this._el_54,throwOnChange);
    const currVal_58:any = 'primary';
    this._Label_56_3.check_color(currVal_58,throwOnChange,false);
    this._Label_56_3.detectChangesInternal(this,this._el_56,throwOnChange);
    const currVal_60:any = this.context.passwordRetype;
    this._NgModel_59_4.check_model(currVal_60,throwOnChange,false);
    this._NgModel_59_4.detectChangesInternal(this,this._el_59,throwOnChange);
    this._NgControlStatus_59_6.detectChangesInternal(this,this._el_59,throwOnChange);
    const currVal_67:any = 'Retype Password';
    this._TextInput_59_7.check_placeholder(currVal_67,throwOnChange,false);
    const currVal_68:any = 'password';
    this._TextInput_59_7.check_type(currVal_68,throwOnChange,false);
    this._TextInput_59_7.detectChangesInternal(this,this._el_59,throwOnChange);
    const currVal_70:any = '';
    this._Button_65_4.check_block(currVal_70,throwOnChange,false);
    if (this._Button_65_4.detectChangesInternal(this,this._el_65,throwOnChange)) { this._appEl_65.componentView.markAsCheckOnce(); }
    const currVal_72:any = '';
    this._Button_68_4.check_block(currVal_72,throwOnChange,false);
    if (this._Button_68_4.detectChangesInternal(this,this._el_68,throwOnChange)) { this._appEl_68.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset(([] as any[]));
        this._Item_14_4.context._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset(([] as any[]));
        this._Item_14_4.context._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset(([] as any[]));
        this._Item_22_4.context._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset(([] as any[]));
        this._Item_22_4.context._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset(([] as any[]));
        this._Item_30_4.context._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset(([] as any[]));
        this._Item_30_4.context._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_38_1.dirty) {
        this._query_Button_38_1.reset(([] as any[]));
        this._Item_38_4.context._buttons = this._query_Button_38_1;
        this._query_Button_38_1.notifyOnChanges();
      }
      if (this._query_Icon_38_2.dirty) {
        this._query_Icon_38_2.reset(([] as any[]));
        this._Item_38_4.context._icons = this._query_Icon_38_2;
        this._query_Icon_38_2.notifyOnChanges();
      }
      if (this._query_Button_46_1.dirty) {
        this._query_Button_46_1.reset(([] as any[]));
        this._Item_46_4.context._buttons = this._query_Button_46_1;
        this._query_Button_46_1.notifyOnChanges();
      }
      if (this._query_Icon_46_2.dirty) {
        this._query_Icon_46_2.reset(([] as any[]));
        this._Item_46_4.context._icons = this._query_Icon_46_2;
        this._query_Icon_46_2.notifyOnChanges();
      }
      if (this._query_Button_54_1.dirty) {
        this._query_Button_54_1.reset(([] as any[]));
        this._Item_54_4.context._buttons = this._query_Button_54_1;
        this._query_Button_54_1.notifyOnChanges();
      }
      if (this._query_Icon_54_2.dirty) {
        this._query_Icon_54_2.reset(([] as any[]));
        this._Item_54_4.context._icons = this._query_Icon_54_2;
        this._query_Icon_54_2.notifyOnChanges();
      }
      this._TextInput_19_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_14_4.context.ngAfterContentInit(); }
      this._TextInput_27_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_22_4.context.ngAfterContentInit(); }
      this._TextInput_35_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_30_4.context.ngAfterContentInit(); }
      this._TextInput_43_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_38_4.context.ngAfterContentInit(); }
      this._TextInput_51_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_46_4.context.ngAfterContentInit(); }
      this._TextInput_59_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_54_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_65_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_68_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._NgControlStatus_19_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_19_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_19_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_19_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_19_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_19_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_17:any = this._NgControlStatus_27_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_27_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_27_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_27_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_27_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_27_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_28:any = this._NgControlStatus_35_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_35,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_35_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_35,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_35_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_35,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_35_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_35,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_35_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_35,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_35_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_35,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_39:any = this._NgControlStatus_43_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_43,'ng-untouched',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_43_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_43,'ng-touched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_43_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_43,'ng-pristine',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_43_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_43,'ng-dirty',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_43_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_43,'ng-valid',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_43_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_43,'ng-invalid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_50:any = this._NgControlStatus_51_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_51,'ng-untouched',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_51_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_51,'ng-touched',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_51_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_51,'ng-pristine',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_51_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_51,'ng-dirty',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_51_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_51,'ng-valid',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_51_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_51,'ng-invalid',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_61:any = this._NgControlStatus_59_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_59,'ng-untouched',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = this._NgControlStatus_59_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementClass(this._el_59,'ng-touched',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = this._NgControlStatus_59_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_59,'ng-pristine',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._NgControlStatus_59_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_59,'ng-dirty',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this._NgControlStatus_59_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_59,'ng-valid',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_59_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_59,'ng-invalid',currVal_66);
      this._expr_66 = currVal_66;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_19_4.context.ngOnDestroy();
    this._TextInput_19_7.context.ngOnDestroy();
    this._NgModel_27_4.context.ngOnDestroy();
    this._TextInput_27_7.context.ngOnDestroy();
    this._NgModel_35_4.context.ngOnDestroy();
    this._TextInput_35_7.context.ngOnDestroy();
    this._NgModel_43_4.context.ngOnDestroy();
    this._TextInput_43_7.context.ngOnDestroy();
    this._NgModel_51_4.context.ngOnDestroy();
    this._TextInput_51_7.context.ngOnDestroy();
    this._NgModel_59_4.context.ngOnDestroy();
    this._TextInput_59_7.context.ngOnDestroy();
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.userName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.lastName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_59_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.passwordRetype = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_65_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_68_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignUp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SignUp> {
  if ((renderType_SignUp === (null as any))) { (renderType_SignUp = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_SignUp,{})); }
  return new _View_SignUp0(viewUtils,parentInjector,declarationEl);
}